name: Test and coverage

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.24.2'

      # TODO(cemreyavuz): remove this step once the app starts reading the site data from db 
      - name: Create site folder for tests
        run: mkdir ./test-site

      - name: Run tests
        run: go test ./... -race -coverprofile=coverage.out -covermode=atomic
        env:
          DEPLOY_TO_VM_ASSETS_DIR: "./test-assets"
          DEPLOY_TO_VM_SITE_DIR: "./test-site"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}